<?php

/**
 * @file
 * {{ LABEL }} icons module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_page_bottom().
 */
function {{ NAME }}_icons_page_bottom(array &$page_bottom) {
  $inline_defs = \Drupal::service('{{ NAME }}_icons.manager')->getInlineDefs();
  if ($inline_defs) {
    $page_bottom['{{ NAME }}_icons_nline_defs'] = [
      '#type' => 'inline_template',
      '#template' => '<svg{{ attributes }}>{{ defs|raw }}</svg>',
      '#context' => [
        'attributes' => new Attribute(['class' => ['visually-hidden']]),
        'defs' => $inline_defs,
      ],
    ];
  }
}

/**
 * Implements callback_allowed_values_function().
 */
function {{ NAME }}_icons_allowed_icon_values() {
  return \Drupal::service('{{ NAME }}_icons.manager')->getSelectOptions();
}
