version: 2
updates:
  - package-ecosystem: npm
    directory: /public_html/themes/custom/{{ NAME }}/
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: thursday # Drupal security patches are released on Wednesday evenings.
    versioning-strategy: lockfile-only
    ignore:
      # Ignore drupal/core-* packages since they should all be updated together
      # and hence should be done manually. Remove this if
      # dependabot/dependabot-core#1190 is resolved.
      - dependency-name: drupal/core-*
