<?php

/**
 * @file
 * File Browser UI improvements.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_form_FORM_ID_alter() for entity_browser_browse_NAME_modal_form.
 *
 * Adds file browser grid selection to custom entity_browser views.
 *
 * function {{ NAME }}_file_browser_form_entity_browser_browse_NAME_modal_form_alter(&$form) {
 *  file_browser_attach_file_browser_to_form($form);
 * }
 */

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter() for entity_browser_file.
 */
function {{ NAME }}_file_browser_field_widget_entity_browser_file_form_alter(&$element, FormStateInterface $form_state, $context) {
  $element['#attached']['library'][] = '{{ NAME }}_file_browser/entity_browser.file_browser';

  $validators = $context['widget']->getFileValidators(TRUE);
  // Rename entity_browser validation for image resolution so that the
  // 'file_upload_help' themeable renders it.
  if (isset($validators['entity_browser_file_validate_image_resolution'])) {
    $validators['file_validate_image_resolution'] = $validators['entity_browser_file_validate_image_resolution'];
    unset($validators['entity_browser_file_validate_image_resolution']);
  }

  $cardinality = $context['items']
    ->getFieldDefinition()
    ->getFieldStorageDefinition()
    ->getCardinality();

  $element['help'] = [
    '#type' => 'inline_template',
    '#template' => '
      <div{{ attributes }}>
        {{ content|render|replace({ "<br />": " ", "<br/>": " " })|raw }}
      </div>
    ',
    '#context' => [
      'attributes' => new Attribute(['class' => ['description']]),
      'content' => [
        '#theme' => 'file_upload_help',
        '#upload_validators' => $validators,
        '#cardinality' => $cardinality,
      ],
    ],
    '#weight' => -1,
  ];

  $element['entity_browser']['#weight'] = -2;
}
