<?php

/**
 * @file
 * {{ LABEL }} helper module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_editor_js_settings_alter().
 */
function {{ NAME }}_helper_editor_js_settings_alter(array &$settings) {
  if (isset($settings['editor']['formats']['full_html']) && $settings['editor']['formats']['full_html']['editor'] == 'ckeditor') {
    $settings['editor']['formats']['full_html']['editorSettings']['bodyClass'] = 'c-text-body';
  }
}

/**
 * Implements hook_preprocess_HOOK() for views-view.html.twig.
 */
function {{ NAME }}_helper_preprocess_views_view(&$variables) {
  $extenders = $variables['view']->display_handler->getExtenders();

  if (isset($extenders['inview'])) {
    $extenders['inview']->preprocessViewsView($variables);
  }
}

/**
 * Implements hook_page_bottom().
 */
function {{ NAME }}_helper_page_bottom(array &$page_bottom) {
  $inline_defs = \Drupal::service('{{ NAME }}_helper.icons')->getInlineDefs();
  if ($inline_defs) {
    $page_bottom['{{ NAME }}_inline_defs'] = [
      '#type' => 'inline_template',
      '#template' => '<svg{{ attributes }}>{{ defs|raw }}</svg>',
      '#context' => [
        'attributes' => new Attribute(['class' => ['visually-hidden']]),
        'defs' => $inline_defs,
      ],
    ];
  }
}
