<?php

/**
 * @file
 * {{ LABEL }} helper module.
 */

/**
 * Implements hook_editor_js_settings_alter().
 */
function {{ NAME }}_helper_editor_js_settings_alter(array &$settings) {
  foreach (array_keys($settings['editor']['formats']) as $format) {
    if ($settings['editor']['formats'][$format]['editor'] == 'ckeditor') {
      $settings['editor']['formats'][$format]['editorSettings']['bodyClass'] = 'c-text-body c-text-body--editor';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for views-view.html.twig.
 */
function {{ NAME }}_helper_preprocess_views_view(&$variables) {
  $extenders = $variables['view']->display_handler->getExtenders();

  if (isset($extenders['inview'])) {
    $extenders['inview']->preprocessViewsView($variables);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for block_content_form.
 */
function {{ NAME }}_helper_form_block_content_form_alter(array &$form) {
  // Hide block_content block description field from those who cannot administer
  // blocks since they may assume this is the block title.
  $form['info']['#access'] = \Drupal::currentUser()->hasPermission('administer blocks');
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function {{ NAME }}_helper_menu_links_discovered_alter(&$links) {
  $editable_menus = [
    'footer',
    'main',
  ];

  // Remove static module-defined menu links on front-end, editable menus to
  // avoid conflicts with menu overrides config syncing.
  foreach ($links as $key => $link) {
    if (
      strpos($key, 'menu_link_content:') === FALSE &&
      isset($link['menu_name']) && in_array($link['menu_name'], $editable_menus)
    ) {
      unset($links[$key]);
    }
  }
}

/**
 * Implements hook_library_info_alter().
 */
function {{ NAME }}_helper_library_info_alter(&$libraries, $extension) {
  $path = drupal_get_path('module', '{{ NAME }}_helper');

  switch ($extension) {
    case 'seven':
      $libraries['global-styling']['css']['component']["/$path/css/seven/components/form.css"] = [];
      break;

    case 'paragraphs':
      $libraries['drupal.paragraphs.widget']['css']['theme']["/$path/css/paragraphs/theme/widget.css"] = [];
      $libraries['paragraphs-dragdrop']['css']['theme']["/$path/css/paragraphs/theme/dragdrop.css"] = [];
      break;
  }
}
