# Schema for configuration files of the {{ LABEL }} Helper module.

views.display_extender.inview:
  type: views_display_extender
  label: 'In-view views display extender settings'
  mapping:
    selector:
      type: string
      label: Selector
      nullable: true
    ratio:
      type: float
      label: Ratio
